### PR TITLE
Crashlytics: Add support for `setUserId`

### LINKED ISSUE #43: Support `setUserId` call in `CrashlyticsKotlin`
The `setUserId` call is not exposed in `CrashlyticsKotlin`. See https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#set-user-ids and https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#set-user-ids.

### PR DESCRIPTION
**Pull request by findjigar**
Fixes #43

### CODE REVIEW

File: crashlytics/src/commonMain/kotlin/co/touchlab/crashkios/crashlytics/CrashlyticsCalls.kt [hunk 1]
```diff
@@ -5,6 +5,8 @@ interface CrashlyticsCalls {
     fun sendHandledException(throwable: Throwable)
     fun sendFatalException(throwable: Throwable)
     fun setCustomValue(key: String, value: Any)
+
```
Comment (kpgalligan) [inline crashlytics/src/commonMain/kotlin/co/touchlab/crashkios/crashlytics/CrashlyticsCalls.kt:8]: Minor, but we should either drop the extra line, or add them between the others.

**Review by kpgalligan — APPROVED** [review]
Made a comment about the empty line, but otherwise it's good.
